- name: load cert vars
  include_vars: roles/gen-cert/vars/main.yml

- name: set hostname
  hostname: name=k8s-master.{{ ansible_default_ipv4.address | regex_replace('\.', '') }}

- name: init k8s install dir
  file: path={{ K8S_WORK_DIR }}/{{ item }} owner=root group=root mode=0755 state=directory
  with_items:
    - bin
    - cfg
    - ssl
    - manifests

- name: init kube-dns works dir
  file: path={{ DNS_WORKDIR }} owner=root group=root mode=0755 state=directory

- name: Install yum epel-release
  yum: name=epel-release state=present

- name: install flannel
  yum: name=flannel state=latest

- name: copy cert to master
  copy: src={{CERT_DIR}}/{{ item }} dest={{ K8S_WORK_DIR }}/ssl/{{ item }} owner=root group=root mode=0644
  with_items:
    - ca.pem
    - apiserver.pem
    - apiserver-key.pem

- name: copy k8s-master commands
  copy: src={{ item }} dest={{ K8S_WORK_DIR }}/bin/{{ item }} owner=root group=root mode=0755
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kubectl
    - kube-dns
    - kube-scheduler

- name: copy k8s-master config file
  template: src={{ item }} dest={{ K8S_WORK_DIR }}/cfg/{{ item }} mode=644
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-dns
    - kube-scheduler

- name: copy services file
  template: src={{ item }} dest=/usr/lib/systemd/system/{{ item }} mode=644
  with_items:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-dns.service
    - kube-scheduler.service

- name: link k8s-master commands
  file: src={{ K8S_WORK_DIR }}/bin/{{ item }} dest=/usr/bin/{{ item }} state=link
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kubectl
    - kube-dns
    - kube-scheduler   

- name: start k8s services and flanneld
  systemd: name={{ item }} state=restarted daemon_reload=yes enabled=True
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - flanneld
    - kube-dns

- name: copy lvs scripts
  template: src=lvs_real dest=/usr/local/bin/lvs_real mode=0755

- name: start lvs vip
  command: /usr/local/bin/lvs_real start
  changed_when: false

- name: "k8s-master install succuess"
  debug: msg="k8s-master install succuess"